#
# Generated - do not edit!
#
# NOCDDL
#
CND_BASEDIR=`pwd`
# DPSK3_PIC24 configuration
CND_ARTIFACT_DIR_DPSK3_PIC24=dist/DPSK3_PIC24/production
CND_ARTIFACT_NAME_DPSK3_PIC24=pic24.production.hex
CND_ARTIFACT_PATH_DPSK3_PIC24=dist/DPSK3_PIC24/production/pic24.production.hex
CND_PACKAGE_DIR_DPSK3_PIC24=${CND_DISTDIR}/DPSK3_PIC24/package
CND_PACKAGE_NAME_DPSK3_PIC24=pic24.tar
CND_PACKAGE_PATH_DPSK3_PIC24=${CND_DISTDIR}/DPSK3_PIC24/package/pic24.tar
